import { MetadataRoute } from 'next';

/**
 * robots.txt configuration for search engine crawlers
 * This file is automatically generated by Next.js at /robots.txt
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://clashconverter.com';

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/_next/', '/static/'],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
